// <auto-generated />
using CIS106ExceptionHandling.repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS106ExceptionHandling.Migrations
{
    [DbContext(typeof(EhDbContext))]
    [Migration("20240305135552_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CIS106ExceptionHandling.models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Claw hammer for general purpose use",
                            Name = "Hammer",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Set of Phillips and flat-head screwdrivers",
                            Name = "Screwdriver Set",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cordless drill with rechargeable battery",
                            Name = "Drill",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Set of needle-nose and lineman's pliers",
                            Name = "Pliers",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 5,
                            Description = "25-foot retractable tape measure",
                            Name = "Tape Measure",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hand saw for cutting wood and plastic",
                            Name = "Saw",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Set of paint rollers and tray",
                            Name = "Paint Roller Set",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Assorted nails for various applications",
                            Name = "Nails Assortment",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Assorted screws for various applications",
                            Name = "Screws Assortment",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "10-foot extension cord for indoor use",
                            Name = "Extension Cord",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Retractable utility knife with replaceable blades",
                            Name = "Utility Knife",
                            Price = 4.49m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Protective eyewear for use in workshops",
                            Name = "Safety Glasses",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Pair of heavy-duty work gloves",
                            Name = "Work Gloves",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Manual caulking gun for applying sealant",
                            Name = "Caulk Gun",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Set of locks for interior doors",
                            Name = "Door Lock Set",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Assorted grit sandpaper for sanding surfaces",
                            Name = "Sandpaper Assortment",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 17,
                            Description = "LED flashlight with adjustable focus",
                            Name = "Flashlight",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Compact cordless screwdriver with magnetic tip",
                            Name = "Cordless Screwdriver",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Waterproof sealant for sealing gaps and cracks",
                            Name = "Caulk",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Electronic stud finder for locating studs in walls",
                            Name = "Stud Finder",
                            Price = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
